"""empty message

Revision ID: b1800b20f537
Revises: 34bf413ef90a
Create Date: 2024-10-12 16:55:48.289810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1800b20f537'
down_revision = '34bf413ef90a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), server_default='Moscow', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
